app/urls.py
from django.urls import path
from . import views
from django.urls.conf import include
from django.contrib.auth import views as auth_views

app_name = "app"
urlpatterns = [
   path('',views.index,name='index'),
   path('main/',views.main,name='main'),
   path('index/',views.index,name='index'),
   path('logout/', auth_views.LogoutView.as_view(template_name='index.html'), name='logout'),
   path('nasa/',views.nasa.as_view(),name='nasa'),
   path('realtime/',views.realtime.as_view(),name='realtime'),
   path('mydata/',views.mydataView.as_view(),name='mydata'),
   #path('mydata/',views.mydata,name='mydata'),
   path('chart/', views.BatteryStateView.as_view(), name="chart"),
   path('nchart/',views.nasaView.as_view(),name='nchart'),
   path('mchart/',views.myView.as_view(),name='mchart'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('app.urls')),
]



users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = "users"
urlpatterns = [
   path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
   path('logout/', auth_views.LogoutView.as_view(template_name='app/index.html'), name='logout'),
   path('', auth_views.LogoutView.as_view(template_name='index.html'), name='logout'),
   
]

app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        
        <title>index</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <!---<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#page-top">Start Bootstrap</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>
                        <li class="nav-item"><a class="nav-link" href="#portfolio">Portfolio</a></li>
                        <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav> ---> 
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">Battery SOH Prediction</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5">
                        <p class="text-white-75 mb-5">Team 7</p>
                        <a class="btn btn-primary btn-xl" href="{% url 'users:login' %}">Login</a>
                    </div>
                </div>
            </div>
        </header>
       
    </body>
</html>

app/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        
        <title>main</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <style>

        </style>
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'app:index' %}">Home</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    
                </div>
            </div>
        </nav> 
        <header class="masthead">
            <section class="page-section" id="services">
                <div class="container px-4 px-lg-5">
                    <h2 class="text-white mt-0" style="text-align:center" >Service</h2>
                    <hr class="divider" />
                    <div class="row gx-4 gx-lg-5">
                        <div class="col-lg-3 col-md-6 text-center">
                            <div class="mt-5">
                                <div class="mb-2"><i class="bi-gem fs-1 text-primary"></i></div>
                                <h3 class="text-white font-weight-bold"><a href="{% url 'app:mydata' %}" style="color:white">Collected Data</a></h3>
                                <p class="text-muted mb-0"></p>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 text-center">
                            <div class="mt-5">
                                <div class="mb-2"><i class="bi-laptop fs-1 text-primary"></i></div>
                                <h3 class="text-white font-weight-bold"><a href="{% url 'app:realtime' %}" style="color:white">State</a></h3>
                                <p class="text-muted mb-0"></p>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 text-center">
                            <div class="mt-5">
                                <div class="mb-2"><i class="bi-globe fs-1 text-primary"></i></div>
                                <h3 class="text-white font-weight-bold"><a href="{% url 'app:nasa' %}" style="color:white">Nasa Data</a></h3>
                                <p class="text-muted mb-0"></p>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 text-center">
                            <div class="mt-5">
                                <div class="mb-2"><i class="bi-heart fs-1 text-primary"></i></div>
                                <h3 class="text-white font-weight-bold"><a href="http://www.semiroad.co.kr/" style="color:white">With</a></h3>
                                <p class="text-muted mb-0"></p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
          </div>



app/templates/mydata.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        
        <title>My Dataset</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <style>
            section{
                width: 600px;
                overflow: hidden;
            }
            section article{
                width: 200px;
                height: 100px;
                float: left;
                box-sizing: border-box;
            }

        </style>
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'app:index' %}">Home</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">Logout</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'app:main' %}">Main</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'app:nasa' %}">Nasa Data</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'app:realtime' %}">State</a></li>
                    </ul>
                </div>
            </div>
        </nav> 
        <header class="masthead">
          <div class="container px-4 px-lg-5 h-100">
            <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center" >
                <div class="col-lg-8 align-self-top">
                    <h3 class="text-white font-weight-bold">*battery SOH prediction model 시각화*</h3>
                    <form action="{% url 'app:mydata' %}" method="post">
                        {% csrf_token %}
                        <div>
                          <label for="a" style="color:white">측정 capacity (A)</label>
                          <input type="float" name="a" id="a">
                          <input type="submit" value="submit">
                        </div>
                      </form>
                    <hr class="divider"/>
                    <div>
                        <span id="rest_cycle_id" style="color: white;">{{rest_cycle}}</span>
                    </div>
                </div>
                <div style="display:flex">    
                    <div id='container2' style="flex:1;padding: 1px 1px 1px 1px;" >
                    
                        <script src="https://code.highcharts.com/highcharts.src.js"></script>
                        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                        
                        <script>
                        $.ajax({
                            url: "{% url 'app:mchart' %}",
                            dataType: 'json',
                            success: function (data) {
                                var element = document.getElementById("rest_cycle_id");
                                element.innerText = "남은 사이클 : " + Math.floor(data.rest_cycle * 100) / 100 + " 회";
                                

                                Highcharts.chart('container2', {
    
                                title: {
                                text: 'Battery Prediction '
                                },
    
                                subtitle: {
                                text: 'prediction'
                                },
    
                                yAxis: {
                                title: {
                                    text: 'capacity'
                                }
                                },
    
                                xAxis: {
                                    title: {
                                    text: 'time'
                                }
                                },
    
                                legend: {
                                layout: 'vertical',
                                align: 'right',
                                verticalAlign: 'middle'
                                },
    
                                plotOptions: {
                                series: {
                                    label: {
                                    connectorAllowed: false
                                    },
                                    pointStart: 1
                                }
                                },
    
                                series: [{
                                name: 'prediction',
                                data: data.copy
                                },{
                                    name: 'actual',
                                    data: data.df['capacity']
                                },],
    
                                responsive: {
                                    rules: [{
                                        condition: {
                                        maxWidth: 200
                                        },
                                        chartOptions: {
                                        legend: {
                                            layout: 'horizontal',
                                            align: 'left',
                                            verticalAlign: 'bottom'
                                            }
                                        }
                                    }]
                                }
    
                                }
                                )

                            }
                        });
                        </script>
                    </div> 
                    
                </div>
            </div>
          </div>
        </header>
       



app/templates/nasa.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        
        <title>NASA Dataset</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <style>
            section{
                width: 600px;
                overflow: hidden;
            }
            section article{
                width: 200px;
                height: 100px;
                float: left;
                box-sizing: border-box;
            }

        </style>
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'app:index' %}">Home</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">Logout</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'app:main' %}">Main</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'app:mydata' %}">Collected</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'app:realtime' %}">State</a></li>
                    </ul>
                </div>
            </div>
        </nav> 
        <header class="masthead">
          <div class="container px-4 px-lg-5 h-100">
            <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center" >
                <div class="col-lg-8 align-self-top">
                    <h3 class="text-white font-weight-bold">*battery SOH prediction model 시각화*</h3>
                        <form action="{% url 'app:nasa' %}" method="post">
                            {% csrf_token %}
                            <div>
                                <label for="a" style="color:white">측정 capacity (A)</label>
                                <input type="float" name="a" id="a">
                                <input type="submit" value="submit">
                            </div>
                        </form>
                    <hr class="divider"/>
                    <div>
                        <span id="rest_cycle_id" style="color: white;">{{rest_cycle}}</span>
                    </div>
                </div>
                <div style="display:flex">
                    <div id="container1" style="flex:1;padding: 1px 1px 1px 1px;" >
                    
                        <script src="https://code.highcharts.com/highcharts.src.js"></script>
                        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                        
                        <script>
                        $.ajax({
                            url: "{% url 'app:nchart' %}",
                            dataType: 'json',
                            success: function (data) {
                                
                                Highcharts.chart('container1', {
    
                                title: {
                                text: 'Battery Prediction'
                                },
    
    
                                yAxis: {
                                title: {
                                    text: 'capacity'
                                }
                                },
    
                                xAxis: {
                                    title: {
                                    text: 'time'
                                }
                                },
    
                                legend: {
                                layout: 'vertical',
                                align: 'right',
                                verticalAlign: 'middle'
                                },
    
                                plotOptions: {
                                series: {
                                    label: {
                                    connectorAllowed: false
                                    },
                                    pointStart: 1
                                }
                                },
    
                                series: [{
                                name: 'actual',
                                data: data.y_test_20
                                },{
                                    name: 'prediction',
                                    data: data.pred
                                }],
    
                                responsive: {
                                rules: [{
                                    condition: {
                                    maxWidth: 200
                                    },
                                    chartOptions: {
                                    legend: {
                                        layout: 'horizontal',
                                        align: 'left',
                                        verticalAlign: 'bottom'
                                    }
                                    }
                                }]
                                }
    
                                }
                                )
                            }
                    });
                        </script>
                    </div>    
                    <div id='container2' style="flex:1;padding: 1px 1px 1px 1px;" >
                    
                        <script src="https://code.highcharts.com/highcharts.src.js"></script>
                        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                        
                        <script>
                        $.ajax({
                            url: "{% url 'app:nchart' %}",
                            dataType: 'json',
                            success: function (data) {
                                
                                Highcharts.chart('container2', {
    
                                title: {
                                text: 'Battery Prediction'
                                },
    
                                subtitle: {
                                text: 'prediction'
                                },
    
                                yAxis: {
                                title: {
                                    text: 'capacity'
                                }
                                },
    
                                xAxis: {
                                    title: {
                                    text: 'time'
                                }
                                },
    
                                legend: {
                                layout: 'vertical',
                                align: 'right',
                                verticalAlign: 'middle'
                                },
    
                                plotOptions: {
                                series: {
                                    label: {
                                    connectorAllowed: false
                                    },
                                    pointStart: 1
                                }
                                },
    
                                series: [{
                                name: 'prediction',
                                data: data.copy
                                },{
                                    name: 'actual',
                                    data: data.df['capacity']
                                }],
    
                                responsive: {
                                rules: [{
                                    condition: {
                                    maxWidth: 200
                                    },
                                    chartOptions: {
                                    legend: {
                                        layout: 'horizontal',
                                        align: 'left',
                                        verticalAlign: 'bottom'
                                    }
                                    }
                                }]
                                }
    
                                }
                                )
                                var element = document.getElementById("rest_cycle_id");
                                element.innerText = "남은 사이클 : " + Math.floor(data.rest_cycle * 100) / 100 + " 회";
                            }
                    });
                        </script>
                    </div> 
                </div>
            </div>
          </div>
        </header>
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
              <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center" >
                  
                </div>
            </div>

       

